openapi: "3.0.0"
info:
  version: 0.0.1
  title: Yet Another Todo App
  description: A simple Todo app to experiment with OpenAPI generated code. 

paths:
  /todos:
    $ref: "./resources/todos.yaml"
    